name: "stock_etl"
version: "1.0.0"
config-version: 2
profile: "stock_etl"

model-paths: ["models"]
target-path: "target"
log-path: "logs"
clean-targets: ["target", "dbt_packages"]

models:
  stock_etl:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
